/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardRouteImport } from './routes/board'
import { Route as NflRouteImport } from './routes/nfl'
import { Route as NhlRouteImport } from './routes/nhl'
import { Route as ApiDeskTickRouteImport } from './routes/api/desk.tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const NflRoute = NflRouteImport.update({
  id: '/nfl',
  path: '/nfl',
  getParentRoute: () => rootRouteImport,
} as any)
const NhlRoute = NhlRouteImport.update({
  id: '/nhl',
  path: '/nhl',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskTickRoute = ApiDeskTickRouteImport.update({
  id: '/api/desk/tick',
  path: '/api/desk/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/nfl': typeof NflRoute
  '/nhl': typeof NhlRoute
  '/api/desk/tick': typeof ApiDeskTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/nfl': typeof NflRoute
  '/nhl': typeof NhlRoute
  '/api/desk/tick': typeof ApiDeskTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/nfl': typeof NflRoute
  '/nhl': typeof NhlRoute
  '/api/desk/tick': typeof ApiDeskTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/board' | '/nfl' | '/nhl' | '/api/desk/tick'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/board' | '/nfl' | '/nhl' | '/api/desk/tick'
  id: '__root__' | '/' | '/board' | '/nfl' | '/nhl' | '/api/desk/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRoute
  NflRoute: typeof NflRoute
  NhlRoute: typeof NhlRoute
  ApiDeskTickRoute: typeof ApiDeskTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfl': {
      id: '/nfl'
      path: '/nfl'
      fullPath: '/nfl'
      preLoaderRoute: typeof NflRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nhl': {
      id: '/nhl'
      path: '/nhl'
      fullPath: '/nhl'
      preLoaderRoute: typeof NhlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk/tick': {
      id: '/api/desk/tick'
      path: '/api/desk/tick'
      fullPath: '/api/desk/tick'
      preLoaderRoute: typeof ApiDeskTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRoute,
  NflRoute: NflRoute,
  NhlRoute: NhlRoute,
  ApiDeskTickRoute: ApiDeskTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
